/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.js' */
"use strict";

module.exports = {
    configs: {
        recommended: require("./configs/recommended"),
    },
    rules: {
        "case-block": require("./rules/case-block"),
        "declaration-order": require("./rules/declaration-order"),
        "func-style": require("./rules/func-style"),
    },
};
