/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.js' */
"use strict";

module.exports = {
    plugins: ["cupcake"],
    rules: {
        "cupcake/case-block": "error",
        "cupcake/declaration-order": "error",
        "cupcake/func-style": "error",
    },
};
