name: test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: "Setup node.js (version: LTS)"
              uses: actions/setup-node@v2.3.0
              with:
                  node-version: lts/*
            - run: npm install
            - run: npm test
